" disable backward compatibility with vi
set nocompatible

filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" General settings
set encoding=utf-8
set fileencoding=utf-8
set t_Co=256                                      " enable 256 colors
set textwidth=0                                   " disable automatic hard line wrapping
                                                  " see http://vim.wikia.com/wiki/Word_wrap_without_line_breaks
set wrapmargin=0
                                                  " http://vim.wikia.com/wiki/Automatic_word_wrapping
set nowrap                                        " no soft wrapping either
set nojoinspaces                                  " prevent 2 consecutive spaces after punctuation on a join (J)

set number                                        " show line numbers
set showmatch                                     " show matching parentheses
set ignorecase                                    " ignore case when searching
set smartcase                                     " SMART CASE: case-sensitive if the search term has a uppercased char
set smarttab                                      " insert tabs on the start of a line according to shiftwidth,
                                                  " not tabstop
set smartindent                                   " smart indent (does the right thing, most of the time)
set hlsearch                                      " highlight search terms
set incsearch                                     " show search matches as you type
set history=1000                                  " remember more commands and search history
set undolevels=1000                               " more undos

set nobackup                                      " don't use backup or swap files
set noswapfile

set wildmenu                                      " show list instead of just autocompleting commands
set whichwrap=b,s,h,l,<,>,[,]                     " also wrap these keys: backspace, navigational
set scrolloff=8                                   " minimum lines to keep above and below cursor
try                                               " set color columns to mark 80 and 120 character limits
  set colorcolumn=80,120
catch
  set colorcolumn=120                             " if 2 color columns are not supported
endtry

set cursorline                                    " highlight current line
" only highlight current line for active window
" see http://vim.wikia.com/wiki/Highlight_current_line
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END


set nofoldenable
set nospell
set timeoutlen=1000 ttimeoutlen=0                 " eliminate delay after pressing Esc or ^c to return to normal mode
                                                  " see https://www.johnhawthorn.com/2012/09/vi-escape-delays/

set ttyfast                                       " enable mouse support
set mouse=a                                       " see http://usevim.com/2012/05/16/mouse/
set ttymouse=xterm2                               " set this to name of your terminal that supports mouse codes:
                                                  " xterm, xterm2, netterm, dec, jsbterm, pterm

syntax on                                         " syntax highlighting pls

set splitbelow                                    " open new split windows to the right and bottom
set splitright

set backspace=indent,eol,start                    " allow backspace to also delete autoindents and newlines

set switchbuf=usetab,newtab                       " see http://vim.wikia.com/wiki/Using_tab_pages

set list                                          " highlight trailing spaces
set listchars=tab:>.,trail:.,extends:#,nbsp:.

set noerrorbells visualbell t_vb=                 " no bell sounds
autocmd GUIEnter * set visualbell t_vb=

cmap w!! w !sudo tee % > /dev/null                " w!! to save file with sudo

" remember last file edit position
" see
" http://askubuntu.com/questions/202075/how-do-i-get-vim-to-remember-the-line-i-was-on-when-i-reopen-a-file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" change cursor shapes according to current mode
" only works in iTerm. tmux optional.
" see http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
if !empty($TMUX)
  " inside a tmux session
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  " not inside a tmux session
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_SR = "\<Esc>]50;CursorShape=2\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Language specific settings
if has('autocmd')
  autocmd filetype html,xml set listchars-=tab:>.
endif

" Keymap
if filereadable(expand('~/.vimrc.keymap'))
  source ~/.vimrc.keymap
endif

" Plugins
if filereadable(expand('~/.vimrc.plugins'))
  source ~/.vimrc.plugins
endif

" Gvim {
if has('gui_running') && has('macunix')
endif
" }

" Custom commands {
function! ToggleBackground_()
  let s:tbg = &background
  if s:tbg == 'dark'
    set background=light
  else
    set background=dark
  endif
endfunction
command! ToggleBackground call ToggleBackground_()
command! ToggleSpellCheck set spell!
command! TogglePaste set paste!
command! ToggleWordWrap set wrap!
command! ToggleLineNumber set number!
command! Resource source ~/.vimrc
command! TabsToSpaces retab
" }

" Colors {
function! ColorLight_()
  colorscheme default
  let g:airline_theme='bubblegum'
  set background=light
  hi ColorColumn ctermbg=LightGray
  hi CursorLine cterm=none ctermbg=LightGray
  hi CursorLineNr ctermbg=LightGray
endfunction
function! ColorDark_()
  call ColorLight_()
  set background=dark
endfunction
function! ColorSolarized_()
  colorscheme solarized
  set background=light
  let g:airline_theme='solarized'
  hi ColorColumn ctermbg=LightGray
  hi CursorLine cterm=none ctermbg=LightGray
  hi CursorLineNr ctermbg=LightGray
endfunction
function! ColorSolarizedDark_()
  call ColorSolarized_()
  set background=dark
endfunction
command! ColorSolarized call ColorSolarized_()
command! ColorSolarizedDark call ColorSolarizedDark_()
command! ColorLight call ColorLight_()
command! ColorDark call ColorDark_()

" default colors
ColorLight
" }

" make sure this is the last line
filetype plugin indent on

