# This file is somehow sourced on every new shell spawn.
# TODO: move these lines into some file that is sourced only once at login.

# CapsLock as Esc and Ctrl
setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'

# Swap Windows and Alt keys.
setxkbmap -option 'altwin:swap_lalt_lwin'

killall tracker-store 2> /dev/null
