#!/bin/bash
# TODO: refactor this monstrosity.
function battery_status {
  local AC_POWER=$(pmset -g ps | head -n1 | cut -d "'" -f 2)
  local BATTERY_PERC=$(pmset -g ps | tail -n1 | cut -d "%" -f 1 | cut -f 2)
  local TIME_REMAINING=$(pmset -g ps | tail -n1 | cut -d ';' -f 3 | cut -d ' ' -f 2)

  # Don't show time remaining when there's no estimate or it's 0:00 (laptop is charged).
  if [[ $TIME_REMAINING = '(no' || $TIME_REMAINING = '0:00' ]]; then
    TIME_REMAINING=""
  else
    TIME_REMAINING=" | $TIME_REMAINING"
  fi

  if [[ $BATTERY_PERC -lt 20 ]]; then
    local COLOR='brightred'
  elif [[ $BATTERY_PERC -lt 70 ]]; then
    local COLOR='brightyellow'
  else
    local COLOR='brightgreen'
  fi

  if [[ $AC_POWER = "AC Power" ]]; then
    local AC_OR_BT='ac'
  else
    local AC_OR_BT='bt'
  fi

  echo -n "#[fg=black,bg=$COLOR] $AC_OR_BT #[fg=$COLOR,bg=black] $BATTERY_PERC%$TIME_REMAINING#[default]"
}

function datetime {
  local COLOR="brightblue"
  echo -n "#[fg=black,bg=$COLOR] dt #[fg=$COLOR,bg=black] $(date +"%H:%M %a %m/%d") #[default]"
}

function disk_space {
  local COLOR="brightmagenta"
  local DISK_FREE=$(df -h | grep "/dev" | head -n1 | awk '{print $5, $4}')
  echo -n "#[fg=black,bg=$COLOR] ds #[fg=$COLOR,bg=black] $DISK_FREE#[default]"
}

function load_avg {
  local COLOR="brightcyan"
  local LOAD_AVG=$(python -c "import sys; print ' '.join(s.strip(',') for s in sys.argv[-3:])" $(uptime))
  echo -n "#[fg=black,bg=$COLOR] lo #[fg=$COLOR,bg=black] $LOAD_AVG#[default]"
}

function separator {
  echo -n "  "
}

function default {
  echo -n "#[default]"
}


default
which pmset 2>&1 > /dev/null && battery_status && separator
disk_space
separator
load_avg
separator
datetime
